sonar.projectKey=amurlaniakea_ssb-validate
sonar.organization=amurlaniakea
sonar.projectName=ssb-validate

sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11

# Excluir artifacts y datos locales del analisis
sonar.exclusions=data/**,**/__pycache__/**,**/*.pyc
